// <auto-generated />
using System;
using Cpro.Forms.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cpro.Forms.Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250416180646_AddDesignerProcessorInFormDesign")]
    partial class AddDesignerProcessorInFormDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cpro.Forms.Data.Models.Designer", b =>
                {
                    b.Property<int>("DesignerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignerId"));

                    b.Property<string>("FormDesignid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignerId");

                    b.HasIndex("FormDesignid");

                    b.ToTable("Designer");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormData", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("FormDatas");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormDesign", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("FormDesigns");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormStatesConfig", b =>
                {
                    b.Property<int>("FormStatesConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormStatesConfigId"));

                    b.Property<string>("FormDesignid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormStatesConfigId");

                    b.HasIndex("FormDesignid");

                    b.ToTable("FormStatesConfig");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormTemplate", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.Processor", b =>
                {
                    b.Property<int>("ProcessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessorId"));

                    b.Property<string>("FormDesignid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcessorId");

                    b.HasIndex("FormDesignid");

                    b.ToTable("Processor");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.Designer", b =>
                {
                    b.HasOne("Cpro.Forms.Data.Models.FormDesign", null)
                        .WithMany("designers")
                        .HasForeignKey("FormDesignid");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormStatesConfig", b =>
                {
                    b.HasOne("Cpro.Forms.Data.Models.FormDesign", null)
                        .WithMany("FormStates")
                        .HasForeignKey("FormDesignid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.Processor", b =>
                {
                    b.HasOne("Cpro.Forms.Data.Models.FormDesign", null)
                        .WithMany("processors")
                        .HasForeignKey("FormDesignid");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormDesign", b =>
                {
                    b.Navigation("FormStates");

                    b.Navigation("designers");

                    b.Navigation("processors");
                });
#pragma warning restore 612, 618
        }
    }
}
