// <auto-generated />
using System;
using Cpro.Forms.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cpro.Forms.Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250406062642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormData", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FormDatas");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormDesign", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FormDesigns");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormStatesConfig", b =>
                {
                    b.Property<string>("label")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FormDesignid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("label", "value");

                    b.HasIndex("FormDesignid");

                    b.ToTable("FormStatesConfig");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormTemplate", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormStatesConfig", b =>
                {
                    b.HasOne("Cpro.Forms.Data.Models.FormDesign", null)
                        .WithMany("FormStates")
                        .HasForeignKey("FormDesignid");
                });

            modelBuilder.Entity("Cpro.Forms.Data.Models.FormDesign", b =>
                {
                    b.Navigation("FormStates");
                });
#pragma warning restore 612, 618
        }
    }
}
